version: "3.3"
services:
  minioS3:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9871:9001
      - 9870:9000  # Minio Server will be available at this port
    command: [ "server", "/data", "--console-address", ":9001" ]
  minioClient:
    depends_on:
      - minioS3
    image: minio/mc # MinIO Client to pre-create bucket
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minioS3:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/openhouse-bucket;
      /usr/bin/mc mb minio/openhouse-bucket;
      /usr/bin/mc policy set public minio/openhouse-bucket;
      tail -f /dev/null
      "
